# Generated by Django 3.2.9 on 2021-11-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
