# Generated by Django 3.2.9 on 2021-11-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
